//定义变量
export const SAVE_USER = "SAVE_USER";
export const REMOVE_REDUX = "REMOVE_REDUX";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
